apiVersion: v2
name: argocd-install
description: Argo CD installation for Togglemaster
type: application
version: 0.1.0
appVersion: "2.13.0"

dependencies:
  - name: argo-cd
    version: 9.5.4
    repository: https://argoproj.github.io/argo-helm
