argo-cd:
  global:
    logging:
      format: json

  configs:
    params:
      server.insecure: true
      server.rootpath: /argocd

  server:
    extraArgs:
      - --rootpath=/argocd
      - --insecure

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      hosts: []
      paths:
        - /argocd
      pathType: Prefix

  dex:
    enabled: false

  notifications:
    enabled: false

  applicationSet:
    enabled: true

  repoServer:
    replicas: 1

  controller:
    replicas: 1
