argo-cd:
  global:
    logging:
      format: json

  configs:
    params:
      server.insecure: true
      server.basehref: /argocd

  server:
    extraArgs:
      - --basehref=/argocd
      - --insecure

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      hosts:
        - ""
      paths:
        - /argocd(/|$)(.*)
      pathType: ImplementationSpecific

  dex:
    enabled: false

  notifications:
    enabled: false

  applicationSet:
    enabled: true

  repoServer:
    replicas: 1

  controller:
    replicas: 1
