name: Deploy Staging

on:
  workflow_dispatch:

jobs:
  # 1. Aplicar Infra
  Terraform:
    uses: Togglemaster/Terraform/.github/workflows/terraform_apply_staging.yaml@main
    secrets: inherit

  # 2. Sincronizar Secrets
  Secrets:
    needs: Terraform
    uses: Togglemaster/Terraform/.github/workflows/secrets_staging.yaml@main
    secrets: inherit

  # 3. CI dos Microserviços (Rodam em paralelo)
  CI_Auth:
    needs: Secrets
    uses: Togglemaster/Auth-Service/.github/workflows/auth_staging.yaml@main

  CI_Flag:
    needs: Secrets
    uses: Togglemaster/Flag-Service/.github/workflows/flag_staging.yaml@main

  CI_Targeting:
    needs: Secrets
    uses: Togglemaster/Targeting-Service/.github/workflows/targeting_staging.yaml@main

  CI_Evaluation:
    needs: Secrets
    uses: Togglemaster/Evaluation-Service/.github/workflows/evaluation_staging.yaml@main

  CI_Analytics:
    needs: Secrets
    uses: Togglemaster/Analytics-Service/.github/workflows/analytics_staging.yaml@main

  # 4. Deploy Final com ArgoCD e Helm
  Deploy_Helm:
    needs: [CI_Auth, CI_Flag, CI_Targeting, CI_Evaluation, CI_Analytics] # Espera os CIs terminarem
    uses: Togglemaster/togglemaster/.github/workflows/helm_deploy.yaml@main
    with:
      environment: 'staging'